repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: lint-cpp
        name: C++ lint (cpplint)
        entry: python ops/script/lint_cpp.py
        language: python
        types: [file]
        files: \.(cc|c|cpp|h|cu|hpp)$
        exclude: (dmlc-core|gputreeshap)
        additional_dependencies:
          - cpplint==1.6.1
      - id: lint-cmake
        name: CMake lint (cmakelint)
        entry: cmakelint --linelength=120 --filter=-convention/filename,-package/stdargs,-readability/wonkycase
        language: python
        types: [file]
        files: (CMakeLists\.txt$|^cmake/.*\.cmake$)
        exclude: (dmlc-core|gputreeshap)
        additional_dependencies:
          - cmakelint
