repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cc|c|cpp|h|cu|hpp)$
        exclude: (dmlc-core|gputreeshap)
  - repo: local
    hooks:
      - id: lint-cpp
        name: C++ lint (cpplint)
        entry: python ops/script/lint_cpp.py
        language: python
        types: [file]
        files: \.(cc|c|cpp|h|cu|hpp)$
        exclude: (dmlc-core|gputreeshap|demo\/c-api|jvm-packages\/xgboost4j\/src\/native\/xgboost4j\..*)
        additional_dependencies:
          - cpplint
      - id: lint-cmake
        name: CMake lint (cmakelint)
        entry: cmakelint --linelength=120 --filter=-convention/filename,-package/stdargs,-readability/wonkycase
        language: python
        types: [file]
        files: (CMakeLists\.txt$|^cmake/.*\.cmake$)
        exclude: (dmlc-core|gputreeshap)
        additional_dependencies:
          - cmakelint
      - id: format-python
        name: Python format + lint (black + isort + pylint)
        entry: python ops/script/lint_python.py --format=1 --type-check=0 --pylint=1 --fix
        language: python
        types: [file]
        files: \.py$
        exclude: (dmlc-core|gputreeshap)
        pass_filenames: false
        additional_dependencies:
          - black
          - isort
          - pylint
