name: Test XGBoost with latest CCCL and RMM

on:
  workflow_dispatch:  # Can be manually triggered
  schedule:
    - cron: "0 7 * * *"  # Run once daily

permissions:
  contents: read

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-latest-cccl-version:
    name: Query the latest version of CCCL
    runs-on: ubuntu-latest
    outputs:
      cccl_version: ${{ steps.query_version_step.outputs.cccl_version }}
    steps:
      - uses: actions/checkout@v4
      - id: query_version_step
        name: Query version
        run: |
          source ops/pipeline/query-latest-cccl.sh
          echo "cccl_version=${CCCL_VERSION}" >> "$GITHUB_OUTPUT"

  test-latest-cccl:
    name: Test building XGBoost with latest CCCL (RC included)
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=linux-amd64-cpu
      - tag=nightly-cccl
    needs: get-latest-cccl-version
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Log into Docker registry (AWS ECR)
        run: bash ops/pipeline/login-docker-registry.sh
      - name: Build XGBoost with latest CCCL
        run: |
          bash ops/pipeline/nightly-test-cccl.sh ${{ needs.get-latest-cccl-version.outputs.cccl_version }}

  get-latest-rmm-version:
    name: Query the latest version of RMM
    runs-on: ubuntu-latest
    outputs:
      rmm_version: ${{ steps.query_version_step.outputs.rmm_version }}
    steps:
      - uses: actions/checkout@v4
      - id: query_version_step
        name: Query version
        run: |
          source ops/pipeline/query-latest-rmm.sh
          echo "rmm_version=${RMM_VERSION}" >> "$GITHUB_OUTPUT"

  test-latest-rmm:
    name: Test building XGBoost with latest nightly version of RMM
    # This job uses the stable CCCL used by RMM and rest of RAPIDS
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=linux-amd64-cpu
      - tag=nightly-rmm
    needs: get-latest-rmm-version
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Log into Docker registry (AWS ECR)
        run: bash ops/pipeline/login-docker-registry.sh
      - name: Build XGBoost with latest RMM
        run: |
          bash ops/pipeline/nightly-test-rmm.sh ${{ needs.get-latest-rmm-version.outputs.rmm_version }}
